forum/urls.py
from django.urls import path
from . import views


app_name = 'forum'
urlpatterns = [
    path("", views.AllTopicsView.as_view(), name="all_topics"),
    path("search/", views.search_topics_or_messages, name="search"),
    path("filter/", views.filter_by_section, name="filter_by_section"),
    path("sorting/", views.sorting_topics, name="sorting_topics"),
    path("add_topic/", views.CreateTopicView.as_view(), name="create_topic"),
    path("<slug:slug>/", views.TopicDetailView.as_view(), name="topic_detail"),
    path("add_message/<int:pk>/", views.AddMessageView.as_view(), name="add_message"),
]

one_map/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tutorial.views import AboutUsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("users/", include("users.urls", namespace='users')),
    path("forum/", include("forum.urls", namespace='forum')),
    path("followers/", include("followers.urls", namespace='followers')),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("", include("tutorial.urls", namespace='tutorial')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tutorial/urls.py
from django.urls import path
from . import views


app_name = 'tutorial'
urlpatterns = [
    path("", views.LessonsView.as_view(), name="main"),
    path("lessons_by_branch/", views.LessonsByBranchView.as_view(), name="lessons_by_branch"),
    path("filter/<int:pk>/", views.FilterByBranchView.as_view(), name="filter_by_branch"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<slug:slug>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path("add_like/<int:pk>/", views.AddLikeView.as_view(), name="add_like"),
    path("remove_like/<int:pk>/", views.RemoveLikeView.as_view(), name="remove_like"),
    path("comment/<int:pk>/", views.AddCommentView.as_view(), name="add_comment"),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("profile/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("edit_profile/<int:pk>/", views.UserUpdateView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/feed/", views.UserFeedView.as_view(), name="feed"),
    path("profile/<int:pk>/subscriptions/", views.UserSubscriptionsView.as_view(), name="subscriptions"),
    path('profile/<int:pk>/followers/', views.UserFollowersView.as_view(), name="followers"),
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>/", views.UserDeleteView.as_view(), name="delete_user"),

    path("password_change/",
         auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html',
                                               success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path("password_change/done/",
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path("password_reset/",
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                              email_template_name='users/password_reset_email.html',
                                              subject_template_name='users/password_reset_subject.txt',
                                              success_url=reverse_lazy('users:password_reset_done'),),
         name="password_reset"),
    path("password_reset_confirm/<uidb64>/<token>",
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),),
         name="password_reset_confirm"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path("password_reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/include/footer.html
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">One Map</p>
    </div>
</footer>

templates/include/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">One Map</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item
          {% if request.resolver_match.namespace == 'tutorial' and url_name != 'lessons_by_branch' %}
            active{% endif %}">
          <a class="nav-link" href="/">Главная
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item {% if url_name == 'lessons_by_branch' %}active{% endif %}">
          <a class="nav-link" href="{% url 'tutorial:lessons_by_branch' %}">Уроки</a>
        </li>
        <li class="nav-item {% if url_name == 'workshop' %}active{% endif %}">
          <a class="nav-link" href="{% url 'forum:all_topics' %}">Форум</a>
        </li>
        <li class="nav-item {% if url_name == 'about_us' %}active{% endif %}">
          <a class="nav-link" href="{% url 'about_us' %}">О нас</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item
          {% if request.resolver_match.namespace == 'users' %}
          active{% endif %}">
            <a class="nav-link" href="{{ request.user.get_absolute_url }}">{{ request.user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Зарегистрироваться</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/include/sidebar.html
<div class="col-md-4">

  <!-- Поиск -->
  <div class="card my-4">
    <h5 class="card-header">Поиск</h5>
    <div class="card-body">
      <form action="{% url 'tutorial:search' %}" method="get">
        <div class="input-group">
          <input type="search" class="form-control" name="q" placeholder="Что найти?">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-secondary" type="button">Поиск</button>
          </span>
        </div>
      </form>
    </div>
  </div>

  <!-- Ветки -->
  <div class="card my-4">
    <h5 class="card-header">Ветки</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled mb-0">
            {% for branch in branchs %}
              <li>
                <a class="branch" href="{% url 'tutorial:filter_by_branch' branch.id %}">{{ branch.name }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Популярные уроки -->
  <div class="card my-4">
    <h5 class="card-header">Популярные</h5>
    <div class="card-body">
      {% for lesson in most_popular_lessons %}
        <p><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></p>
      {% endfor %}
    </div>
  </div>
</div>