forum/urls.py
from django.urls import path
from . import views


app_name = 'forum'
urlpatterns = [
    path("", views.AllTopicsView.as_view(), name="all_topics"),
    path("search/", views.search_topics_or_messages, name="search"),
    path("filter/", views.filter_by_section, name="filter_by_section"),
    path("sorting/", views.sorting_topics, name="sorting_topics"),
    path("add_topic/", views.CreateTopicView.as_view(), name="create_topic"),
    path("<slug:slug>/", views.TopicDetailView.as_view(), name="topic_detail"),
    path("add_message/<int:pk>/", views.AddMessageView.as_view(), name="add_message"),
]

one_map/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tutorial.views import AboutUsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("users/", include("users.urls", namespace='users')),
    path("forum/", include("forum.urls", namespace='forum')),
    path("followers/", include("followers.urls", namespace='followers')),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("", include("tutorial.urls", namespace='tutorial')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tutorial/urls.py
from django.urls import path
from . import views


app_name = 'tutorial'
urlpatterns = [
    path("", views.LessonsView.as_view(), name="main"),
    path("lessons_by_branch/", views.LessonsByBranchView.as_view(), name="lessons_by_branch"),
    path("filter/<int:pk>/", views.FilterByBranchView.as_view(), name="filter_by_branch"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("<slug:slug>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path("add_like/<int:pk>/", views.AddLikeView.as_view(), name="add_like"),
    path("remove_like/<int:pk>/", views.RemoveLikeView.as_view(), name="remove_like"),
    path("comment/<int:pk>/", views.AddCommentView.as_view(), name="add_comment"),
]

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("profile/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("edit_profile/<int:pk>/", views.UserUpdateView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/feed/", views.UserFeedView.as_view(), name="feed"),
    path("profile/<int:pk>/subscriptions/", views.UserSubscriptionsView.as_view(), name="subscriptions"),
    path('profile/<int:pk>/followers/', views.UserFollowersView.as_view(), name="followers"),
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>/", views.UserDeleteView.as_view(), name="delete_user"),

    path("password_change/",
         auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html',
                                               success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path("password_change/done/",
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path("password_reset/",
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                              email_template_name='users/password_reset_email.html',
                                              subject_template_name='users/password_reset_subject.txt',
                                              success_url=reverse_lazy('users:password_reset_done'),),
         name="password_reset"),
    path("password_reset_confirm/<uidb64>/<token>",
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),),
         name="password_reset_confirm"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path("password_reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

tutorial/models.py
from django.db import models
from django.urls import reverse

from users.models import User


# Модель ветки
class Branch(models.Model):
    name = models.CharField("Ветка", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Ветка"
        verbose_name_plural = "Ветки"


# Модель лекции
class Lesson(models.Model):
    authors = models.ManyToManyField(User, related_name='authors')
    title = models.CharField("Урок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to='lessons')
    content = models.TextField("Содержание")
    task = models.TextField("Задание")
    url = models.SlugField(max_length=130, unique=True, null=True)
    draft = models.BooleanField("Черновик", default=False)
    branch = models.ForeignKey(
        Branch, verbose_name="Ветка", related_name="lessons", on_delete=models.SET_NULL, null=True
    )
    date = models.DateField("Дата создания", auto_now_add=True)
    count = models.PositiveIntegerField("Количество просмотров", default=0)
    likes = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = "Урок"
        verbose_name_plural = "Уроки"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("tutorial:lesson_detail", kwargs={"slug": self.url})


# Модель комментария
class Comment(models.Model):
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        "self", verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    lesson = models.ForeignKey(Lesson, verbose_name="Лекция", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

tutorial/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Comment


class CommentForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Comment
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border"})
        }

tutorial/views.py
from django.views.generic.base import View
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import Http404
from django.db.models import F, Q

from .models import Lesson, Branch
from .forms import CommentForm


# Вывод всех уроков постранично
class LessonsView(ListView):
    paginate_by = 3
    model = Lesson
    queryset = Lesson.objects.filter(draft=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['branchs'] = Branch.objects.all()
        context['most_popular_lessons'] = Lesson.objects.order_by('-count')[:3]
        context['url_name'] = 'main'
        return context


# Фильтр уроков по ветке
class FilterByBranchView(ListView):
    template_name = 'tutorial/lesson_list.html'
    paginate_by = 3

    def get_queryset(self):
        branch = Branch.objects.get(id=self.kwargs['pk'])
        print(self.kwargs['pk'])
        return Lesson.objects.filter(branch=branch)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["url_name"] = "filter_by_branch"
        context["branchs"] = Branch.objects.all()
        context["most_popular_lessons"] = Lesson.objects.order_by('-count')[:3]
        return context


# Вывод страницы со всеми уроками, классифицированными по ветке
class LessonsByBranchView(TemplateView):
    template_name = "tutorial/lessons_by_branch.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['branchs'] = Branch.objects.all()
        context['lessons'] = Lesson.objects.filter(draft=False)
        context['url_name'] = 'lessons_by_branch'
        return context


# Вывод страницы урока
class LessonDetailView(DetailView):
    model = Lesson
    slug_field = "url"

    def get_context_data(self, **kwargs):
        Lesson.objects.filter(pk=self.object.pk).update(count=F('count') + 1)
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        context["branchs"] = Branch.objects.all()
        context['most_popular_lessons'] = Lesson.objects.order_by('-count')[:3]
        return context


# Вывод страницы "О нас"
class AboutUsView(TemplateView):
    template_name = "about_us.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_name'] = 'about_us'
        return context


# Добавление лайка к уроку
class AddLikeView(View):
    def get(self, request, pk):
        try:
            if str(pk) in request.COOKIES:
                return redirect('/')
            else:
                lesson = Lesson.objects.get(id=pk)
                lesson.likes += 1
                lesson.save()
                response = redirect(request.META.get('HTTP_REFERER'))
                response.set_cookie(str(pk), "liked")
                return response
        except ObjectDoesNotExist:
            raise Http404


# Удаление лайка к уроку
class RemoveLikeView(View):
    def get(self, request, pk):
        if str(pk) in request.COOKIES:
            lesson = Lesson.objects.get(id=pk)
            lesson.likes -= 1
            lesson.save()
            response = redirect(request.META.get('HTTP_REFERER'))
            response.delete_cookie(str(pk))
            return response


# Добавление комментария к уроку
class AddCommentView(View):
    def post(self, request, pk):
        form = CommentForm(request.POST)
        lesson = Lesson.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.lesson = lesson
            form.save()
        return redirect(lesson.get_absolute_url())


# Вывод результата поиска
class SearchView(ListView):
    template_name = 'tutorial/search_list.html'

    def get_queryset(self):
        return Lesson.objects.filter(Q(title__icontains=self.request.GET.get("q")) |
                                     Q(description__icontains=self.request.GET.get("q")) |
                                     Q(content__icontains=self.request.GET.get("q")) |
                                     Q(task__icontains=self.request.GET.get("q")))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = self.request.GET.get("q")
        context["url_name"] = "search"
        return context

templates/tutorial/lesson_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8">

      <!-- Основная информация урока -->
      <h1 class="mt-4">{{ lesson.title }}</h1>
      <p class="lead">
      {% for author in lesson.authors.all %}
        <a href="{% url 'users:user_detail' author.id %}"> {{ author.username }} </a>
      {% endfor %}
      </p>
      <hr>
      <p>{{ lesson.date }}</p>
      <hr>
      <img class="img-fluid rounded" src="{{ lesson.image.url }}" alt="">
      <p class="lead">{{ lesson.content|safe }}</p>

      <hr>

      <a class="text-secondary" href="{% url 'tutorial:filter_by_branch' lesson.branch.id %}">{{ lesson.branch }}</a>
      &nbsp;
      <!-- Просмотры и лайки -->
      <img src="{% static 'images/views.png' %}" height="25px">
      <span class="text-secondary">{{ lesson.count }}</span>&nbsp; &nbsp;
      {% if user.is_authenticated %}
        {% if lesson.id|stringformat:"s" in request.COOKIES %}
              <a href="{% url 'tutorial:remove_like' lesson.id %}">
                <img src="{% static 'images/liked.png' %}" height="18px"></a>
            {% else %}
              <a href="{% url 'tutorial:add_like' lesson.id %}">
                <img src="{% static 'images/liked.png' %}" height="18px"></a>
            {% endif %}
      {% endif %}
      {{ lesson.likes }}

      <hr>

      <!-- Форма добавления комментария -->
      <div class="card my-4">
        <h5 class="card-header">Оставьте свой комментарий:</h5>
        <div class="card-body">
          <form action="{% url 'tutorial:add_comment' lesson.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label>Имя</label>
              {{ form.name }}
              <label>E-mail</label>
              {{ form.email }}
              <label>Текст комментария</label>
              {{ form.text }}
            </div>
            {{ form.captcha }}
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>

      <!-- Комментарии -->
      {% for comment in lesson.comment_set.all %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{ comment.name }}</h5>
            {{ comment.text }}
          </div>
        </div>
      {% endfor %}
    </div>
    {% include 'include/sidebar.html' %}
  </div>
</div>
{% endblock content %}

templates/tutorial/lesson_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <br>
      <div class="lessons-and-paginate">

        <!-- Уроки -->
        {% for lesson in lesson_list %}
          <div class="card mb-4">
            <img class="card-img-top" src="{{ lesson.image.url }}" alt="Card image cap" width="100px">
            <div class="card-body">
              <h2 class="card-title">{{ lesson.title }}</h2>
              <p class="card-text">{{ lesson.content|safe }}</p>
              <a href="{{ lesson.get_absolute_url }}" class="btn btn-primary">Читать</a>
            </div>
            <div class="card-footer text-muted">
              {{ lesson.date }} &nbsp; &nbsp;
              <a class="text-secondary" href="{% url 'tutorial:filter_by_branch' lesson.branch.id %}">
                {{ lesson.branch }}</a> &nbsp; &nbsp;
              <img src="{% static 'images/views.png' %}" height="25px"> {{ lesson.count }} &nbsp; &nbsp;
              {% if user.is_authenticated %}
                {% if lesson.id|stringformat:"s" in request.COOKIES %}
                  <a href="{% url 'tutorial:remove_like' lesson.id %}">
                    <img src="{% static 'images/liked.png' %}" height="18px"></a>
                {% else %}
                  <a href="{% url 'tutorial:add_like' lesson.id %}">
                    <img src="{% static 'images/liked.png' %}" height="18px"></a>
                {% endif %}
              {% else %}
                <img src="{% static 'images/liked.png' %}" height="18px">
              {% endif %}
            &nbsp; {{ lesson.likes }}
            </div>
          </div>
        {% endfor %}

        <!-- Пагинация -->
        <ul class="pagination justify-content-center mb-4">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">&laquo; </a>
            </li>
            <li>
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt; </a>
            </li>
          {% endif %}

          <li class="page-item disabled">
            <span class="page-link text-muted">
                {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
          </li>

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}"> &gt;</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
    {% include 'include/sidebar.html' %}
  </div>
</div>
{% endblock content %}

templates/tutorial/lessons_by_branch.html
{% extends 'base.html' %}

{% block content %}
<div class="container top-buffer">
    <p> Здесь представлены все уроки по категориям. </p>

    {% for branch in branchs %}
        <h4>{{ branch.name }}</h4>
        <ul class="list-group">
            {% for lesson in branch.lessons.all %}
            <li class="list-group-item"><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></li>
            {% endfor %}
        </ul>
        <br>
    {% endfor %}
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px; }
</style>
{% endblock content %}

templates/tutorial/lessons_of_branch.html
{% load static %}

{% for lesson in lessons %}
  <div class="card mb-4">
    <img class="card-img-top" src="{{ lesson.image.url }}" alt="Card image cap" width="100px">
    <div class="card-body">
      <h2 class="card-title">{{ lesson.title }}</h2>
      <p class="card-text">{{ lesson.content|safe }}</p>
      <a href="{{ lesson.get_absolute_url }}" class="btn btn-primary">Читать</a>
    </div>
    <div class="card-footer text-muted">
      {{ lesson.date }} &nbsp; &nbsp;
      <img src="{% static 'images/views.png' %}" height="25px"> {{ lesson.count }} &nbsp; &nbsp;
      {% if user.is_authenticated %}
        {% if lesson.id|stringformat:"s" in request.COOKIES %}
          <a href="{% url 'tutorial:remove_like' lesson.id %}">
            <img src="{% static 'images/liked.png' %}" height="18px"></a>
        {% else %}
          <a href="{% url 'tutorial:add_like' lesson.id %}">
            <img src="{% static 'images/liked.png' %}" height="18px"></a>
        {% endif %}
      {% else %}
        <img src="{% static 'images/liked.png' %}" height="18px">
      {% endif %}
      {{ lesson.likes }}
    </div>
  </div>
{% endfor %}

templates/tutorial/search_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <br>
      {% for lesson in lesson_list %}
          <div class="card mb-4">
            <img class="card-img-top" src="{{ lesson.image.url }}" alt="Card image cap" width="100px">
            <div class="card-body">
              <h2 class="card-title">{{ lesson.title }}</h2>
              <p class="card-text">{{ lesson.content|safe }}</p>
              <a href="{{ lesson.get_absolute_url }}" class="btn btn-primary">Читать</a>
            </div>
            <div class="card-footer text-muted">
              {{ lesson.date }} &nbsp; &nbsp;
              <a class="text-secondary" href="{% url 'tutorial:filter_by_branch' lesson.branch.id %}">
                {{ lesson.branch }}</a> &nbsp; &nbsp;
              <img src="{% static 'images/views.png' %}" height="25px"> {{ lesson.count }} &nbsp; &nbsp;
              {% if user.is_authenticated %}
                {% if lesson.id|stringformat:"s" in request.COOKIES %}
                  <a href="{% url 'tutorial:remove_like' lesson.id %}">
                    <img src="{% static 'images/liked.png' %}" height="18px"></a>
                {% else %}
                  <a href="{% url 'tutorial:add_like' lesson.id %}">
                    <img src="{% static 'images/liked.png' %}" height="18px"></a>
                {% endif %}
              {% else %}
                <img src="{% static 'tutorial:images/liked.png' %}" height="18px">
              {% endif %}
              {{ lesson.likes }}
            </div>
          </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}