followers/urls.py
from django.urls import path
from . import views

app_name = 'followers'
urlpatterns = [
    path('follow/', views.user_follow, name="user_follow"),
]

forum/urls.py
from django.urls import path
from . import views


app_name = 'forum'
urlpatterns = [
    path("", views.AllTopicsView.as_view(), name="all_topics"),
    path("search/", views.search_topics_or_messages, name="search"),
    path("filter/", views.filter_by_section, name="filter_by_section"),
    path("sorting/", views.sorting_topics, name="sorting_topics"),
    path("add_topic/", views.CreateTopicView.as_view(), name="create_topic"),
    path("<slug:slug>/", views.TopicDetailView.as_view(), name="topic_detail"),
    path("add_message/<int:pk>/", views.AddMessageView.as_view(), name="add_message"),
]

one_map/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tutorial.views import AboutUsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("users/", include("users.urls", namespace='users')),
    path("forum/", include("forum.urls", namespace='forum')),
    path("followers/", include("followers.urls", namespace='followers')),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("", include("tutorial.urls", namespace='tutorial')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("profile/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("edit_profile/<int:pk>/", views.UserUpdateView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/feed/", views.UserFeedView.as_view(), name="feed"),
    path("profile/<int:pk>/subscriptions/", views.UserSubscriptionsView.as_view(), name="subscriptions"),
    path('profile/<int:pk>/followers/', views.UserFollowersView.as_view(), name="followers"),
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>/", views.UserDeleteView.as_view(), name="delete_user"),

    path("password_change/",
         auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html',
                                               success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path("password_change/done/",
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path("password_reset/",
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                              email_template_name='users/password_reset_email.html',
                                              subject_template_name='users/password_reset_subject.txt',
                                              success_url=reverse_lazy('users:password_reset_done'),),
         name="password_reset"),
    path("password_reset_confirm/<uidb64>/<token>",
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),),
         name="password_reset_confirm"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path("password_reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

followers/models.py
from django.conf import settings
from django.db import models


# Модель подписки
class Follow(models.Model):
    user_from = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='rel_from_set'
    )
    user_to = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='rel_to_set'
    )
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

        def __str__(self):
            return f"{self.user_from} follows {self.user_to}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from followers.models import Follow


# Модель пользователя
class User(AbstractUser):
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    avatar = models.ImageField("Файл аватара", upload_to='users', null=True, blank=True)
    site = models.CharField("Сайт", max_length=200, blank=True)
    age = models.IntegerField("Возраст", default=0, blank=True)
    city = models.CharField("Город", max_length=30, blank=True)
    about_us = models.TextField("О себе", blank=True)
    status = models.TextField("Статус", max_length=250, blank=True)
    following = models.ManyToManyField('self', through=Follow, related_name="followers", symmetrical=False)

    class Gender(models.TextChoices):
        MAN = 'M', 'Мужчина'
        WOMAN = 'W', 'Женщина'

    gender = models.CharField(
        "Пол",
        max_length=1,
        choices=Gender.choices,
    )

    class Master(models.TextChoices):
        PHILOSOPHER = 'PHIL', 'Философ'
        PSYCHOLOGIST = 'PS', 'Психолог'
        PROGRAMMER = 'PR', 'Программист'
        ENGINEER = 'ENG', 'Инженер'
        PHYSICIST = 'PHYS', 'Физик'
        BIOLOGIST = 'BI', 'Биолог'
        HISTORIAN = 'HIS', 'Историк'

    master = models.CharField(
        "Мастер",
        max_length=4,
        choices=Master.choices,
        blank=True,
    )

    def __str__(self):
        return self.username

    def delete(self, *args, **kwargs):
        print(self)
        self.is_active = False
        self.save()
        return self

    def get_absolute_url(self):
        return reverse('users:user_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

users/forms.py
from django import forms

followers/views.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from users.models import User
from actions.utils import create_action
from .models import Follow


# Подписывание
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')

    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Follow.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Follow.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ok'})

users/views.py
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, TemplateView
from django.urls import reverse_lazy

from actions.models import Action
from .models import User
from followers.models import Follow


# Создание пользователя
class UserCreateView(CreateView):
    model = User
    fields = ['email', 'username', 'password', 'avatar', 'first_name', 'last_name', 'city', 'gender', 'age', 'master',
              'about_us', 'status']
    success_url = reverse_lazy('users:login')


# Редактирование данных пользователя
class UserUpdateView(UpdateView):
    model = User
    fields = ['email', 'username', 'avatar', 'first_name', 'last_name', 'city', 'gender', 'age', 'master',
              'about_us', 'status']
    template_name_suffix = '_update_form'


# Удаление пользователя
class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('tutorial:main')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)


# Вывод страницы пользователя
class UserDetailView(DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.pk == self.request.user.id:
            actions = Action.objects.exclude(user=self.request.user)
            new_actions = actions.filter(viewed=False)
            new_actions_count = new_actions.count()
            context['new_actions_count'] = new_actions_count
        context['subscriptions'] = Follow.objects.filter(user_from=self.object.pk)
        return context


# Вывод ленты пользователя
class UserFeedView(TemplateView):
    template_name = "users/feed.html"

    def get_context_data(self, **kwargs):
        actions = Action.objects.exclude(user=self.request.user)
        new_actions = actions.filter(viewed=False)
        for action in new_actions:
            action.viewed = True
            action.save()
        following_ids = self.request.user.following.values_list('id', flat=True)
        if following_ids:
            actions = actions.filter(user_id__in=following_ids)
        actions = actions.select_related('user').prefetch_related('target')[:10]
        context = super().get_context_data(**kwargs)
        context['actions'] = actions
        return context


# Вывод подписок пользователя
class UserSubscriptionsView(TemplateView):
    template_name = "users/subscriptions.html"

    def get_context_data(self, pk, **kwargs):
        context = super().get_context_data(**kwargs)
        subscriptions = Follow.objects.filter(user_from=pk)
        users = []
        for subscription in subscriptions:
            user_id = subscription.user_to.id
            user = User.objects.get(id=user_id)
            users.append(user)
        context['subscriptions'] = users
        return context


# Вывод подписчиков пользователя
class UserFollowersView(TemplateView):
    template_name = "users/followers.html"

    def get_context_data(self, pk, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(id=pk)
        followers = user.followers.all()
        context['followers'] = followers
        return context

templates/users/feed.html
{% extends 'base.html' %}

{% block content %}
<div class="container top-buffer">
    <h2>Новости</h2>
    <div id="action-list">
        {% for action in actions %}
            {% include "actions/action_detail.html" %}
        {% endfor %}
    </div>
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock content %}

templates/users/followers.html
{% extends 'base.html' %}

{% block content %}
<div class="container top-buffer">
    {% if not followers %}
        <p>Подписчиков нет</p>
    {% else %}
        <h2>Подписчики</h2>
        {{ followers }}
        {% for follower in followers %}
            <a href="{{ follower.get_absolute_url }}">
                <img src="{{ follower.avatar.url }}" class="rounded-circle" width="50">
                {{ follower.username }}
            </a>
        {% endfor %}
    {% endif %}
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    <p >Возникла ошибка входа.
        Возможно, вы ввели неверное имя пользователя, или пароль. Возможно, ваш аккаунт удален.</p>
</div>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        <p>Ваша учетная запись не имеет доступа к этой странице. Чтобы продолжить,
           пожалуйста, войдите в систему с учетной записью, у которой есть доступ.</p>
    {% else %}
        <p>Пожалуйста, войдите в систему, чтобы просмотреть эту страницу.</p>
    {% endif %}
{% endif %}

<div class="container top-buffer">
    <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}

        <div class="modal-footer">
            <a href="{% url 'users:register' %}" class="btn btn-light">Зарегистрироваться</a>
            <a href="{% url 'users:password_reset' %}" class="btn btn-light">Забыли пароль?</a>
            <input type="submit" value="Войти" class="btn btn-primary">
            <input type="hidden" name="next" value="{{ next }}">
        </div>
    </form>
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock %}

templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div id="success_change">
    <p>Пароль успешно изменен</p>
    <p>Вы можете перейти в свой профиль по <a href="{{ user.get_absolute_url }}">ссылке</a></p>
</div>

<style>
#success_change {
   margin:20px;
}
</style>
{% endblock %}

templates/users/password_change_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container top-buffer">
  <h3>Изменение пароля</h3>
  <form method="post">
  {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Обновить пароль</button>
  </form>
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="container top-buffer">
  <p>
    Ваш пароль был установлен. Вы можете <a href="{% url 'users:login' %}">войти</a> сейчас.
  </p>
</div>

<style>
.top-buffer {
  margin: 20;
}
</style>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
{% if validlink %}
  <h3>Изменение пароля</h3>
  <form method="post">
  {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
      </div>
    {% endfor %}

    <div class="modal-footer">
      <button type="submit" class="btn btn-primary">Изменить пароль</button>
    </div>
  </form>
{% else %}
  <p>
    Ссылка для сброса пароля была недействительной, возможно, потому, что она уже использовалась.
    Пожалуйста, запросите новый сброс пароля.
  </p>
{% endif %}
{% endblock %}

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container top-buffer">
  <p>
    Мы отправили вам по электронной почте инструкции по установке пароля. Вы должны получить их в ближайшее время.
  </p>
  <p>
    Если вы не получили электронное письмо, пожалуйста, убедитесь, что вы ввели адрес, с которым зарегистрировались,
    и проверьте папку со спамом.
  </p>
</div>

<style>
.top-buffer {
  margin: 20;
}
</style>
{% endblock %}

templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container top-buffer">
  <h3>Забыли пароль</h3>
  <form method="post">
  {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
      </div>
    {% endfor %}

    <div class="modal-footer">
      <button type="submit" class="btn btn-primary">Подтвердить</button>
    </div>
  </form>
</div>

<style>
.top-buffer {
            margin-top:20px;
            margin-bottom:20px;
}
</style>
{% endblock %}

templates/users/subscriptions.html
{% extends 'base.html' %}

{% block content %}
<div class="container top-buffer">
    {% if not followers %}
        <p>Подписок нет</p>
    {% else %}
        <h2>Подписки</h2>
        {% for subscription in subscriptions %}
            <a href="{{ subscription.get_absolute_url }}">
                <img src="{{ subscription.avatar.url }}" class="rounded-circle" width="50">
                {{ subscription.username }}
            </a>
        {% endfor %}
    {% endif %}
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock content %}

templates/users/user_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post" class="top-buffer">
    {% csrf_token %}
        <p>Вы действительно хотите удалить свой профиль?</p>
        <a href="{{ request.META.HTTP_REFERER }}" type="button" class="btn btn-primary">Отмена</a>
        <input type="submit" value="Да" class="btn btn-light">
    </form>
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock %}

templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<script src= "{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
  $(document).ready(function() {

      // Подписка на пользователя
      $("#follow").click(function(e) {
          $.post({
              url: '{% url 'followers:user_follow' %}',
              data: {
                     'csrfmiddlewaretoken': '{{ csrf_token }}',
                     id: $(this).data('id'),
                     action: $(this).data('action')
                   },
              success: function(data) {
                  if (data['status'] == 'ok') {
                      var previous_action = $('#follow').data('action');
                    }

                    // Изменение действия на противоположное
                    $('#follow').data('action', previous_action == 'follow' ? 'unfollow' : 'follow');

                    // Изменение текста ссылки
                    $('#follow').text(previous_action == 'follow' ? 'Отписаться' : 'Подписаться');

                    // Обновление количества подписчиков
                    var previous_followers = parseInt(
                    $('p.count .total').text());
                    $('p.count .total').text(
                    previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1
                    );
                  }
          });
      });
  });
</script>

<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">

          <!-- Левая часть профиля -->
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                  {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" alt="User" class="rounded-circle" width="150">
                  {% else %}
                    <img src="{% static 'images/noavatar.png' %}" alt="User" class="rounded-circle" width="150">
                  {% endif %}
                  <div class="mt-3">
                    <h4>{{ user.username }}</h4>
                    {% if user.master %}
                      <span class="badge badge-pill badge-secondary">{{ user.get_master_display }}</span>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>

            {% if not request.user %}
              <button data-id="{{ user.id }}"
                data-action="{% if request.user in user.followers.all %}un{% endif %}follow"
                id = "follow"
                class="button btn btn-primary">
                {% if request.user not in user.followers.all %}
                  Подписаться
                {% else %}
                  Отписаться
                {% endif %}
              </button>
            {% endif %}

            {% if user.id == request.user.id %}
              <div class="col mt-3">
                <a type="button" class="btn btn-primary btn-sm" href="{% url 'users:feed' pk=user.id %}">
                  Новости <span class="badge badge-light">{{ new_actions_count }}</span></a>
                <a class="btn btn-secondary btn-sm" href="{% url 'users:subscriptions' pk=user.id %}">
                  Подписки <span class="badge badge-light">{{ subscriptions.count }}</span></a>
                <a class="btn btn-secondary btn-sm" href="{% url 'users:followers' user.id %}">
                  Подписчики <span class="badge badge-light total">{{ user.followers.count }}</span>
                </a>
              </div>
            {% else %}
              <div class="col mt-3">
                <a class="btn btn-secondary btn-sm" href="{% url 'users:subscriptions' pk=user.id %}">
                  Подписки <span class="badge badge-light">{{ subscriptions.count }}</span></a>
                <a class="btn btn-secondary btn-sm" href="{% url 'users:followers' user.id %}">
                  Подписчики <span class="badge badge-light total">{{ user.followers.count }}</span>
                </a>
              </div>
            {% endif %}

            {% if user.status %}
              <div class="card mt-3">
                <h6 class="mb-0 text-center">Статус</h6>
                <p class="col text-secondary">{{ user.status }}</p>
              </div>
            {% endif %}

            {% if user.about_us %}
              <div class="card mt-3">
              <h6 class="mb-0 text-center">Обо мне</h6>
                <p class="col text-secondary">{{ user.about_us }}</p>
              </div>
            {% endif %}

            {% if user.site %}
              <div class="card mt-3">
                  <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline">
                                        <circle cx="12" cy="12" r="10"></circle>
                                        <line x1="2" y1="12" x2="22" y2="12"></line>
                                        <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10
                                        15.3 15.3 0 0 1 4-10z"></path></svg>
                                        {{ user.site }}</h6>
              </div>
            {% endif %}

            {% if request.user.pk == user.pk %}
              <div class="col mt-3">
                <a href="{% url 'users:password_change' %}">Изменить пароль</a>
              </div>
              <div class="col">
                <a href="{% url 'users:delete_user' user.pk %}">Удалить профиль</a>
              </div>
            {% endif %}
          </div>

            <!-- Правая часть профиля -->
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">{% if user.last_name %}Полное имя{% else %}Имя{% endif %}</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {% if user.last_name %}{{ user.get_full_name }}{% else %}{{ user.first_name }}{% endif %}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Пол</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.get_gender_display }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Возраст</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.age }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.email }}
                    </div>
                  </div>
                  <hr>
                  {% if user.city  %}
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0">Город</h6>
                      </div>
                      <div class="col-sm-9 text-secondary">
                        {{ user.city }}
                      </div>
                    </div>
                    <hr>
                  {% endif %}
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Зарегистрирован</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.date_joined }}
                    </div>
                  </div>
                  <hr>
                  {% if user.id == request.user.id %}
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " target="__blank" href="{% url 'users:edit_profile' user.pk %}">
                        Редактировать</a>
                    </div>
                  </div>
                  {% endif %}
                </div>
              </div>

              {% if user.messages.all %}
                <div class="row gutters-sm">
                  <div class="col-sm-12 mb-3">
                    <div class="card h-100">
                      <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">
                        Сообщения пользователя</i></h6>
                      <hr>
                      {% for message in user.messages.all %}
                        <div class="row">
                          <div class="col-sm-3">
                            <h6 class="mb-0">{{ message.datetime }}</h6>
                          </div>
                          <div class="col-sm-9 text-secondary">
                            {{ message.text }}
                          </div>
                          <div class="col-sm-3">
                          <a href="{{ message.topic.get_absolute_url }}">{{ message.topic.title }}</a>
                          </div>
                        </div>
                        <hr>
                      {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              {% endif %}
            </div>
        </div>
    </div>
</div>

<style type="text/css">
body {
    margin-top:20px;
    text-align: left;
}
.main-body {
    padding: 15px;
}

.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}
.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}
.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}

.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.h-100 {
    height: 100%!important;
}

.shadow-none {
    box-shadow: none!important;
}
</style>
{% endblock content %}

templates/users/user_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container top-buffer">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}

        <div class="modal-footer">
            <input type="submit" class="btn btn-primary" value="Зарегистрироваться">
        </div>
    </form>
</div>

<style>
.top-buffer { margin-top:20px;
              margin-bottom:20px;
}
</style>
{% endblock %}

templates/users/user_update_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container top-buffer">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}

        <div class="modal-footer">
            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-light">Отмена</a>
            <input type="submit" value="Обновить" class="btn btn-primary">
        </div>
    </form>
</div>

<style>
.top-buffer {
    margin-top: 20px;
    margin-bottom: 20px;
}
</style>
{% endblock %}