forum/urls.py
from django.urls import path
from . import views


app_name = 'forum'
urlpatterns = [
    path("", views.AllTopicsView.as_view(), name="all_topics"),
    path("search/", views.search_topics_or_messages, name="search"),
    path("filter/", views.filter_by_section, name="filter_by_section"),
    path("sorting/", views.sorting_topics, name="sorting_topics"),
    path("add_topic/", views.CreateTopicView.as_view(), name="create_topic"),
    path("<slug:slug>/", views.TopicDetailView.as_view(), name="topic_detail"),
    path("add_message/<int:pk>/", views.AddMessageView.as_view(), name="add_message"),
]

one_map/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tutorial.views import AboutUsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("users/", include("users.urls", namespace='users')),
    path("forum/", include("forum.urls", namespace='forum')),
    path("followers/", include("followers.urls", namespace='followers')),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("", include("tutorial.urls", namespace='tutorial')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("profile/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("edit_profile/<int:pk>/", views.UserUpdateView.as_view(), name="edit_profile"),
    path("profile/<int:pk>/feed/", views.UserFeedView.as_view(), name="feed"),
    path("profile/<int:pk>/subscriptions/", views.UserSubscriptionsView.as_view(), name="subscriptions"),
    path('profile/<int:pk>/followers/', views.UserFollowersView.as_view(), name="followers"),
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>/", views.UserDeleteView.as_view(), name="delete_user"),

    path("password_change/",
         auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html',
                                               success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path("password_change/done/",
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path("password_reset/",
         auth_views.PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                              email_template_name='users/password_reset_email.html',
                                              subject_template_name='users/password_reset_subject.txt',
                                              success_url=reverse_lazy('users:password_reset_done'),),
         name="password_reset"),
    path("password_reset_confirm/<uidb64>/<token>",
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete'),),
         name="password_reset_confirm"),
    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path("password_reset/complete/",
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

forum/models.py
from django.db import models
from django.urls import reverse

from users.models import User


# Модель секции
class Section(models.Model):
    name = models.CharField("Раздел", max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"


# Модель топика
class Topic(models.Model):
    url = models.SlugField(max_length=130, unique=True, null=True)
    section = models.ForeignKey(Section, verbose_name="Секция",
                                null=True, related_name="topics", on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name="Автор",
                               related_name="topics", on_delete=models.PROTECT)
    title = models.CharField("Название", max_length=100)
    text = models.TextField("Основной текст", null=True, max_length=1000)
    views = models.IntegerField(default=0)
    datetime = models.DateTimeField("Дата и время создания", auto_now_add=True, blank=True)
    solved = models.BooleanField("Решено", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("forum:topic_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Топик"
        verbose_name_plural = "Топики"


# Модель сообщения
class Message(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="messages")
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name="messages")
    text = models.TextField("Текст сообщения", max_length=1000)
    datetime = models.DateTimeField("Дата и время добавления", auto_now=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

forum/views.py
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import F, Q
from django.shortcuts import render
from django.http import HttpResponseNotFound

from actions.utils import create_action
from .models import Section, Topic, Message


# Вывод всех топиков постранично
class AllTopicsView(ListView):
    paginate_by = 5
    model = Topic
    ordering = ['-datetime']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sections'] = Section.objects.all()
        context['url_name'] = 'workshop'
        return context


# Фильтр топиков по секции
def filter_by_section(request):
    print(request.GET.get('section_id'))
    section_id = request.GET.get('section_id')
    try:
        section = Section.objects.get(id=section_id)
    except:
        return HttpResponseNotFound('<h1>Нет топиков в этой секции</h1>')

    topics_of_section = Topic.objects.filter(section=section)
    return render(request, 'forum/topics_of_section.html', {'topics': topics_of_section})


# Сортировка топиков
def sorting_topics(request):
    sorting = request.GET.get('sorting')
    active_section_id = request.GET.get('active_section_id')

    if not active_section_id:
        if sorting == "latest":
            topic_list = Topic.objects.order_by('-datetime')
        elif sorting == "popular":
            topic_list = Topic.objects.order_by('-views')
        elif sorting == "solved":
            topic_list = Topic.objects.order_by('-solved')
        elif sorting == "unsolved":
            topic_list = Topic.objects.order_by('solved')
        elif sorting == "no_replies_yet":
            topic_list = Topic.objects.filter(messages=None).order_by('-datetime')
        else:
            return HttpResponseNotFound('<h1>Page not found</h1>')

        return render(request, 'forum/sorting_list.html', {'topic_list': topic_list})

    else:
        try:
            section = Section.objects.get(id=active_section_id)
        except:
            return HttpResponseNotFound('<h1>Page not found</h1>')

        topics_of_section = Topic.objects.filter(section=section)

        if sorting == "latest":
            topic_list = topics_of_section.order_by('-datetime')
        elif sorting == "popular":
            topic_list = topics_of_section.order_by('-count')
        elif sorting == "solved":
            topic_list = topics_of_section.order_by('-solved')
        elif sorting == "unsolved":
            topic_list = topics_of_section.order_by('solved')
        elif sorting == "no_replies_yet":
            topic_list = topics_of_section.filter(topic__messages=None).order_by('-datetime')
        else:
            return HttpResponseNotFound('<h1>Page not found</h1>')

        return render(request, 'forum/sorting_list.html', {'topic_list': topic_list})


# Вывод страницы топика
class TopicDetailView(DetailView):
    model = Topic
    slug_field = "url"

    def get_context_data(self, **kwargs):
        Topic.objects.filter(pk=self.object.pk).update(views=F('views') + 1)
        context = super().get_context_data(**kwargs)
        context['sections'] = Section.objects.all()
        context['url_name'] = "workshop"
        return context


# Создание топика
class CreateTopicView(CreateView):
    model = Topic
    fields = ["title", "text", "section"]

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.url = str(Topic.objects.last().pk + 1)
        self.object.save()
        create_action(self.request.user, 'create topic', self.object)
        return HttpResponseRedirect(self.get_success_url())


# Добавление сообщения
class AddMessageView(CreateView):
    model = Message
    fields = ["text"]

    def post(self, request, pk):
        form = self.get_form()

        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.author = self.request.user
            self.object.topic = Topic.objects.get(id=pk)
            self.object.save()
            create_action(self.request.user, 'write message', self.object)
            return HttpResponseRedirect(self.get_success_url())


# Поиск топиков и сообщений
def search_topics_or_messages(request):
    query = request.GET.get("q")
    topics = Topic.objects.filter(Q(title__icontains=query) |
                                  Q(text__icontains=query))
    messages = Message.objects.filter(Q(text__icontains=query))

    return render(request, "forum/search_result.html", {'topics': topics, 'messages': messages,
                                                        'q': query})

templates/forum/search_result.html
{% load static %}

{% if topics or messages %}
    {% if topics %}
    <h5>Совпадения в названиях топиков:</h5>
        {% for topic in topics %}
            <div class="card mb-2">
                <div class="card-body p-2 p-sm-3">
                    <div class="media forum-item">
                        <a href="{% url 'users:user_detail' topic.author.id %}">
                            <img src="{% if topic.author.avatar %} {{ topic.author.avatar.url }}
                            {% else %} {% static 'images/noavatar.png' %} {% endif %}"
                            class="mr-3 rounded-circle" width="50" alt="User" />
                        </a>
                        <div class="media-body">
                            <h6><a href="{{ topic.get_absolute_url }}" class="text-body">{{ topic.title }}</a></h6>
                            <p class="text-secondary">
                                {{ topic.text }}
                            </p>
                            <p class="text-muted"><a href="{% url 'users:user_detail' topic.author.id %}">
                                {{ topic.author }}</a> replied <span class="text-secondary font-weight-bold">
                                {{ topic.datetime }}</span>
                            </p>
                        </div>
                        <div class="text-muted small text-center align-self-center">
                            <span class="d-none d-sm-inline-block"><i class="far fa-eye"></i> {{ topic.views }}</span>
                            <span><i class="far fa-comment ml-2"></i> {{ topic__messages.count }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    {% if messages %}
    <br>
    <h5>Совпадения в сообщениях:</h5>
        {% for message in messages %}
        <div class="card mb-2">
            <div class="card-body p-2 p-sm-3">
                <div class="media forum-item">
                    <a href="{% url 'users:user_detail' message.author.id %}">
                        <img src="{% if message.author.avatar %} {{ message.author.avatar.url }}
                        {% else %} {% static 'images/noavatar.png' %} {% endif %}"
                        class="mr-3 rounded-circle" width="50" alt="User" />
                    </a>
                    <div class="media-body">
                        <p class="text-body">
                            {{ message.text }}
                        </p>
                        <p class="text-muted"><a href="{% url 'users:user_detail' message.author.id %}">
                            {{ message.author }}</a> replied <span class="text-secondary font-weight-bold">
                            {{ message.datetime }}</span>
                        </p>
                        <span class="text-secondary">Топик: </span>
                        <a href="{{ message.topic.get_absolute_url }}">{{ message.topic.title }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif %}

{% else %}
    <h5>По вашему запросу ничего не найдено</h5>
{% endif %}

templates/forum/sorting_list.html
{% load static %}

{% for topic in topic_list %}
    <div class="card mb-2">
        <div class="card-body p-2 p-sm-3">
            <div class="media forum-item">
                <a href="{% url 'users:user_detail' topic.author.id %}"><img src="{% if topic.author.avatar %}
                {{ topic.author.avatar.url }} {% else %} {% static 'images/noavatar.png' %} {% endif %}"
                class="mr-3 rounded-circle" width="50" alt="User" /></a>
                <div class="media-body">
                    <h6><a href="{{ topic.get_absolute_url }}" class="text-body">{{ topic.title }}</a></h6>
                    <p class="text-secondary">
                        {{ topic.text }}
                    </p>
                    <p class="text-muted"><a href="{% url 'users:user_detail' topic.author.id %}">{{ topic.author }}</a>
                        replied <span class="text-secondary font-weight-bold">{{ topic.datetime }}</span>
                    </p>
                </div>
                <div class="text-muted small text-center align-self-center">
                    <span class="d-none d-sm-inline-block"><i class="far fa-eye"></i> {{ topic.views }}</span>
                    <span><i class="far fa-comment ml-2"></i> {{ topic__messages.count }}</span>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

templates/forum/topic_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Первое сообщение топика -->
<div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
    <a href="{% url 'forum:all_topics' %}" class="btn btn-light btn-sm mb-3 has-icon"><i class="fa fa-arrow-left mr-2">
    </i>Назад</a>
    <div class="card mb-2">
        <div class="card-body">
            <div class="media forum-item">
                <a href="{% url 'users:user_detail' topic.author.id %}" class="card-link">
                    <img src="{% if topic.author.avatar %} {{ topic.author.avatar.url }}
                    {% else %} {% static 'images/noavatar.png' %} {% endif %}" class="rounded-circle" width="50"
                    alt="User"/>
                    <small class="d-block text-center text-muted">{{ topic.author.master }}</small>
                </a>
                <div class="media-body ml-3">
                    <a href="{% url 'users:user_detail' topic.author.id %}" class="text-secondary">
                    {{ topic.author.username}}</a>
                    <small class="text-muted ml-2">{{ topic.datetime}}</small>
                    <h5 class="mt-1">{{ topic.title }}</h5>
                    <div class="mt-3 font-size-sm">
                        <p>{{ topic.text }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Остальные сообщения -->
    {% for message in topic.messages.all %}
    <div class="card mb-2">
        <div class="card-body">
            <div class="media forum-item">
                <a href="{% url 'users:user_detail' topic.author.id %}" class="card-link">
                    <img src="{% if message.author.avatar %} {{ message.author.avatar.url }}
                    {% else %} {% static 'images/noavatar.png' %} {% endif %}" class="rounded-circle" width="50"
                    alt="User" />
                    <small class="d-block text-center text-muted">{{ message.author.master }}</small>
                </a>
                <div class="media-body ml-3">
                    <a href="{% url 'users:user_detail' topic.author.id %}" class="text-secondary">
                    {{ message.author.username }}</a>
                    <small class="text-muted ml-2"> {{ message.datetime }}</small>
                    <div class="mt-3 font-size-sm">
                        <p>{{ message.text }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    <!-- Кнопка добавления сообщения -->
    <a href="{% url 'forum:add_message' topic.id %}" class="btn btn-primary has-icon btn-block">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-plus mr-2">
        <line x1="12" y1="5" x2="12" y2="19"></line>
        <line x1="5" y1="12" x2="19" y2="12"></line>
        </svg>
        НОВОЕ СООБЩЕНИЕ
    </a>
    </div>
</div>
{% endblock content %}

templates/forum/topic_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<script src= "{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $(".section").click(function(e) {
            $.get({
                url: '{% url "forum:filter_by_section" %}',
                data: { section_id: e.target.id },
                success: function(data) {
                    $('.section').each(function(i) {
                        if ($(this).hasClass('active')) {
                                $(this).removeClass('active')
                             }
                    });
                    $(e.target).addClass('active')
                    $('.inner-main-body').empty();
                    $('.inner-main-body').append(data);
                }
            });
        });

        $("#select_sort").change(function() {
            var sorting = $('#select_sort').val();
            var active_section_id = {{ active_section_id }}

            $.get({
                url: '{% url 'forum:sorting_topics' %}',
                data: { sorting: sorting,
                        active_section_id: active_section_id
                },
                success: function(data) {
                    $(".inner-main-body").empty();
                    $('.inner-main-body').append(data);
                }
            });
        });

        $("#search").keypress(function(event) {
        if (event.which == 13) {
                $.get({
                    url: '{% url 'forum:search' %}',
                    data: { q: $('#search').val() },
                    success: function(data) {
                         $(".inner-main-body").empty();
                         $('.inner-main-body').append(data);
                     }
                });
            }
        });
    });
</script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css"
      integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />

<div class="container">
    <div class="main-body p-0">
        <div class="inner-wrapper">
            <div class="inner-sidebar">

                <!-- Кнопка создания нового топика -->
                <div class="inner-sidebar-header justify-content-center">
                    <a href="{% url 'forum:create_topic' %}" class="btn btn-primary has-icon btn-block">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="feather feather-plus mr-2">
                        <line x1="12" y1="5" x2="12" y2="19"></line>
                        <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                        НОВЫЙ ТОПИК
                    </a>
                </div>

                <!-- Секции -->
                <div class="inner-sidebar-body p-0">
                    <div class="p-3 h-100" data-simplebar="init">
                        <div class="simplebar-wrapper" style="margin: -16px;">
                            <div class="simplebar-mask">
                                <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                    <div class="simplebar-content" style="padding: 16px;">
                                        <nav class="nav nav-pills nav-gap-y-1 flex-column">
                                            {% for section in sections %}
                                                <a href="#" id="{{ section.id }}"
                                                   class="nav-link nav-link-faded has-icon section">
                                                   {{ section.name }}</a>
                                            {% endfor %}
                                        </nav>
                                    </div>
                                </div>
                            </div>
                            <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                        </div>
                        <div class="simplebar-track simplebar-vertical" style="visibility: visible;">
                        <div class="simplebar-scrollbar"
                        style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);"></div></div>
                    </div>
                </div>
            </div>

            <!-- Сортровки и фильтры -->
            <div class="inner-main">
                <div class="inner-main-header">
                    <a class="nav-link nav-icon rounded-circle nav-link-faded mr-3 d-md-none" href="#"
                       data-toggle="inner-sidebar"><i class="material-icons">arrow_forward_ios</i></a>
                    <select id="select_sort" class="custom-select custom-select-sm w-auto mr-1">
                        <option value="latest">Последние</option>
                        <option value="popular">Популярные</option>
                        <option value="solved">Закрытые</option>
                        <option value="unsolved">Открытые</option>
                        <option value="no_replies_yet">Без ответов</option>
                    </select>
                    <span class="input-icon input-icon-sm ml-auto w-auto">
                        <input type="search" id="search"
                               class="form-control form-control-sm bg-gray-200 border-gray-200 shadow-none mb-4 mt-4"
                               name="q" placeholder="Поиск по форуму" />
                    </span>
                </div>

                <!-- Топики -->
                <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                    {% for topic in topic_list %}
                        <div class="card mb-2">
                            <div class="card-body p-2 p-sm-3">
                                <div class="media forum-item">
                                    <a href="{% url 'users:user_detail' topic.author.id %}">
                                        <img src="{% if topic.author.avatar %} {{ topic.author.avatar.url }}
                                        {% else %} {% static 'images/noavatar.png' %} {% endif %}"
                                        class="mr-3 rounded-circle" width="50" alt="User" /></a>
                                    <div class="media-body">
                                        <h6><a href="{{ topic.get_absolute_url }}" class="text-body">{{ topic.title }}
                                        </a></h6>
                                        <p class="text-secondary">
                                            {{ topic.text }}
                                        </p>
                                        <p class="text-muted"><a href="{% url 'users:user_detail' topic.author.id %}">
                                            {{ topic.author }}</a> replied
                                            <span class="text-secondary font-weight-bold">
                                            {{ topic.datetime }}</span></p>
                                    </div>
                                    <div class="text-muted small text-center align-self-center">
                                        <span class="d-none d-sm-inline-block"><i class="far fa-eye">
                                        </i> {{ topic.views }}</span>
                                        <span><i class="far fa-comment ml-2">
                                        </i> {{ topic.messages.all|length }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Пагинация -->
                <ul class="pagination justify-content-center mb-4">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                          <a class="page-link" href="?page=1">&laquo; </a>
                        </li>
                        <li>
                          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lt; </a>
                        </li>
                    {% endif %}

                  <li class="page-item disabled">
                    <span class="page-link text-muted">
                        {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
                  </li>

                  {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}"> &gt;</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
                  </li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

<script src= "{% static 'vendor/jquery/jquery.min.js' %}"></script>
<style type="text/css">
body {
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;
}
.inner-wrapper {
    position: relative;
    height: calc(100vh - 3.5rem);
    transition: transform 0.3s;
}
@media (min-width: 992px) {
    .sticky-navbar .inner-wrapper {
        height: calc(100vh - 3.5rem - 48px);
    }
}

.inner-main,
.inner-sidebar {
    position: absolute;
    top: 0;
    bottom: 0;
    display: flex;
    flex-direction: column;
}
.inner-sidebar {
    left: 0;
    width: 235px;
    border-right: 1px solid #cbd5e0;
    background-color: #fff;
    z-index: 1;
}
.inner-main {
    right: 0;
    left: 235px;
}
.inner-main-footer,
.inner-main-header,
.inner-sidebar-footer,
.inner-sidebar-header {
    height: 3.5rem;
    border-bottom: 1px solid #cbd5e0;
    display: flex;
    align-items: center;
    padding: 0 1rem;
    flex-shrink: 0;
}
.inner-main-body,
.inner-sidebar-body {
    padding: 1rem;
    overflow-y: auto;
    position: relative;
    flex: 1 1 auto;
}
.inner-main-body .sticky-top,
.inner-sidebar-body .sticky-top {
    z-index: 999;
}
.inner-main-footer,
.inner-main-header {
    background-color: #fff;
}
.inner-main-footer,
.inner-sidebar-footer {
    border-top: 1px solid #cbd5e0;
    border-bottom: 0;
    height: auto;
    min-height: 3.5rem;
}
@media (max-width: 767.98px) {
    .inner-sidebar {
        left: -235px;
    }
    .inner-main {
        left: 0;
    }
    .inner-expand .main-body {
        overflow: hidden;
    }
    .inner-expand .inner-wrapper {
        transform: translate3d(235px, 0, 0);
    }
}

.nav .show>.nav-link.nav-link-faded, .nav-link.nav-link-faded.active, .nav-link.nav-link-faded:active,
.nav-pills .nav-link.nav-link-faded.active, .navbar-nav .show>.nav-link.nav-link-faded {
    color: #3367b5;
    background-color: #c9d8f0;
}
.nav-pills .nav-link.active, .nav-pills .show>.nav-link {
    color: #fff;
    background-color: #467bcb;
}
.nav-link.has-icon {
    display: flex;
    align-items: center;
}
.nav-link.active {
    color: #467bcb;
}
.nav-pills .nav-link {
    border-radius: .25rem;
}
.nav-link {
    color: #4a5568;
}

.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}
.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}
</style>
{% endblock content %}

templates/forum/topics_of_section.html
{% load static %}

{% for topic in topics %}
    <div class="card mb-2">
        <div class="card-body p-2 p-sm-3">
            <div class="media forum-item">
                <a href="{% url 'users:user_detail' topic.author.id %}">
                    <img src="{% if topic.author.avatar %} {{ topic.author.avatar.url }}
                    {% else %} {% static 'images/noavatar.png' %} {% endif %}"
                    class="mr-3 rounded-circle" width="50" alt="User"/>
                </a>
                <div class="media-body">
                    <h6><a href="{{ topic.get_absolute_url }}" class="text-body">{{ topic.title }}</a></h6>
                    <p class="text-secondary">
                        {{ topic.text }}
                    </p>
                    <p class="text-muted"><a href="{% url 'users:user_detail' topic.author.id %}">{{ topic.author }}</a>
                        replied <span class="text-secondary font-weight-bold">{{ topic.datetime }}</span></p>
                </div>
                <div class="text-muted small text-center align-self-center">
                    <span class="d-none d-sm-inline-block"><i class="far fa-eye"></i> {{ topic.views }}</span>
                    <span><i class="far fa-comment ml-2"></i> {{ topic.messages.all|length }}</span>
                </div>
            </div>
        </div>
    </div>
{% endfor %}